name: GameDevPortfolio
description: Web app portfolio


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # services
  provider: ^5.0.0
  youtube_player_iframe: ^4.0.4
  http: ^0.13.5
  video_player: ^2.5.3
  visibility_detector: ^0.3.3

  #ui tool
  pointer_interceptor: ^0.9.3+3

  # icons
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: MelodiMono
      fonts:
        - asset: fonts/BLMelodyMono-Regular.otf
          weight: 400
        - asset: fonts/BLMelodyMono-Medium.otf
          weight: 500
        
    - family: Melodi
      fonts:
        - asset: fonts/BLMelody-ExtraLight.otf
          weight: 200
        - asset: fonts/BLMelody-Light.otf
          weight: 300
        - asset: fonts/BLMelody-Regular.otf
          weight: 400
        - asset: fonts/BLMelody-Medium.otf
          weight: 500
        - asset: fonts/BLMelody-SemiBold.otf
          weight: 600

  uses-material-design: true
